Repository mottmacdonaldglobal/Sandbox, pull requests merged in 2022-02, with the labels that each got.

#38 Folder renaming
  SandboxCore/GeometryHelper/PointsHelper.cs
  SandboxCore/SpreadSheetHelper/DataSheet.cs
  SandboxCore/SpreadSheetHelper/NpoiExtension.cs
  SandboxCore/SpreadSheetHelper/SpreadSheetReader.cs
  SandboxCore/SpreadSheetHelper/SpreadSheetWriter.cs
  SandboxGh/Attributes/ButtonAttribute.cs
  SandboxGh/Utility/CreateDictionary.cs
  SandboxGh/Utility/DictParam.cs
  SandboxGh/Utility/EditValueDictionary.cs
  SandboxGh/Utility/FilterDictionary.cs
  SandboxGh/Utility/GH_Dict.cs
  SandboxGh/Utility/MergeDictionary.cs
  SandboxGh/Utility/ReadDictionary.cs
Labels: refactor :hammer:

#39 Dev/mibi/proj update
  SandboxCore/SandboxCore.csproj
  SandboxCore/app.config
  SandboxCore/packages.config
  SandboxDynExplicitNode/SandboxDynExplicitNode.csproj
  SandboxDynExtensions/SandboxDynExtensions.csproj
  SandboxDynZeroTouch/SandboxDynZeroTouch.csproj
  SandboxDynZeroTouch/app.config
Labels: refactor :hammer:

#40 Release draft action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement :sparkles:

#48 Added DeleteKeyDict component
  SandboxDynExplicitNode/manifests/pkg.json
  SandboxGh/Resources.Designer.cs
  SandboxGh/Resources.resx
  SandboxGh/Resources/DeleteKeyDictIcon.png
  SandboxGh/Utility/DeleteKeyDictionary.cs
  doc/tools/UtilityTools.md
Labels: enhancement :sparkles:, grasshopper :cricket:

#49 Created the ValueType component for the dictionary project
  SandboxGh/Resources.Designer.cs
  SandboxGh/Resources.resx
  SandboxGh/Resources/ValueTypeDictIcon.png
  SandboxGh/Utility/ValueTypeDictionary.cs
Labels: enhancement :sparkles:, grasshopper :cricket:

#50 Created the SortKey dictionary node
  SandboxGh/Resources.Designer.cs
  SandboxGh/Resources.resx
  SandboxGh/Resources/SortByKeyDictIcon.png
  SandboxGh/Utility/SortKeyDictionary.cs
Labels: enhancement :sparkles:, grasshopper :cricket:

#51 PR checks and metrics
  .github/workflows/publish-on-release.yml
  .github/workflows/pull-request-checks.yml
  README.md
Labels: enhancement :sparkles:

#55 Dictionary to Json
  .github/workflows/pull-request-checks.yml
  SandboxGh/Resources.Designer.cs
  SandboxGh/Resources.resx
  SandboxGh/Resources/JSONFromDictIcon.png
  SandboxGh/Utility/CreateDictionary.cs
  SandboxGh/Utility/DeleteKeyDictionary.cs
  SandboxGh/Utility/EditValueDictionary.cs
  SandboxGh/Utility/FilterDictionary.cs
  SandboxGh/Utility/GH_Dict.cs
  SandboxGh/Utility/JSONFromDictionary.cs
  SandboxGh/Utility/MergeDictionary.cs
  SandboxGh/Utility/ValueTypeDictionary.cs
Labels: enhancement :sparkles:, grasshopper :cricket:

#54 Dictionary to CSV
  README.md
  SandboxCore/SandboxCore.csproj
  SandboxCore/Utility/DictionaryHelper.cs
  SandboxCore/packages.config
  SandboxDynZeroTouch/Excel/Writer.cs
  SandboxGh/Attributes/ButtonAttribute.cs
  SandboxGh/ExampleFiles/ExampleFile.gh
  SandboxGh/Resources.Designer.cs
  SandboxGh/Resources.resx
  SandboxGh/Resources/CSVFromDictIcon.png
  SandboxGh/Utility/CSVFromDictionary .cs
  SandboxGh/Utility/CSVFromDictionaryButton.cs
  SandboxGh/Utility/CreateDictionary.cs
  SandboxGh/Utility/CreateDictionaryButton.cs
  SandboxGh/Utility/GH_Dict.cs
  SandboxGh/Utility/JSONFromDictionary.cs
  SandboxGh/Utility/ValueTypeDictionary.cs
  doc/guides/OurVision.md
  doc/tools/UtilityTools.md
Labels: enhancement :sparkles:, grasshopper :cricket:, refactor :hammer:

#64 Fixed bug for RemoveCollinearPoints
  SandboxGh/Geometry/RemoveCollinearPoints.cs
Labels: bug :bug:, grasshopper :cricket:
